# Site settings
title: Quiver
email: hey@letsquiver.com
description: > # this means to ignore newlines until "baseurl:"
 Dating for the rest of us.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: letsquiver
facebook_username:  letsquiver

# Build settings
markdown: kramdown
